ChangeLog, Makefile.in:   Remove libext2fs.info*, not just libext2fs.info*.gz.  Add an   uninstall-doc-libs target. ChangeLog, Makefile.in, compile_et.1, compile_et.sh.in:   Makefile.in: Fix bug where my_dir was set incorrectly.  Install the   	et_c.awk and et_h.awk files in $(datadir)/et (i.e., /usr/share/et)   	directory.  Change to use new installation directory variables   	convention.  Fix uninstall rules to take $(DESTDIR) into account.   compile_et.1: Change man page to reflect the fact that compile_et is   	now a awk/sed script, not a yacc script.   compile_et.sh.in: Look in $(datadir)/et for et_c.awk and et_h.awk; if   	not found, look in the build directory.  Add error checking for   	non-existent input file. ChangeLog, Makefile.in, mk_cmds.sh.in:   Makefile.in: Install the ct_c.awk and ct_c.sed files in $(datadir)/ss   	(i.e., /usr/share/ss) directory.  Change to use new installation   	directory variables convention.  Fix uninstall rules to take   	$(DESTDIR) into account.   mk_cmds.sh.in: Look in $(datadir)/ss for ct_c.awk and ct_c.sed; if not   	found, look in the build directory.  Add error checking for   	non-existent input file. ChangeLog, Makefile.in:   Makefile.in: Change to use new installation directory variables   	convention.  Fix uninstall rules to take $(DESTDIR) into account.

diff --git a/lib/et/compile_et.sh.in b/lib/et/compile_et.sh.in
--- a/lib/et/compile_et.sh.in
+++ b/lib/et/compile_et.sh.in
@@ -2,10 +2,30 @@
 #
 #
 AWK=@AWK@
-DIR=@ET_DIR@
+DIR="${DIR-@datadir@/et}"
+ET_DIR=@ET_DIR@
+
+if test "x$1" = x ; then
+    echo "Usage: compile_et file"
+    exit 1
+fi
+
+if test ! -f $DIR/et_h.awk -o ! -f $DIR/et_c.awk ; then
+    DIR=$ET_DIR
+#    echo "Falling back to $DIR..."
+    if test ! -f $DIR/et_h.awk -o ! -f $DIR/et_c.awk ; then
+	echo "compile_et: Couldn't find compile_et's template files."
+	exit 1
+    fi
+fi
 
 ROOT=`echo $1 | sed -e s/.et$//`
 BASE=`basename $ROOT`
+
+if test ! -f $ROOT.et ; then
+    echo "compile_et: $ROOT.et: File not found"
+    exit 1;
+fi
 
 $AWK -f ${DIR}/et_h.awk outfile=${BASE}.h $ROOT.et
 $AWK -f ${DIR}/et_c.awk outfile=${BASE}.c $ROOT.et
diff --git a/lib/ss/mk_cmds.sh.in b/lib/ss/mk_cmds.sh.in
--- a/lib/ss/mk_cmds.sh.in
+++ b/lib/ss/mk_cmds.sh.in
@@ -2,14 +2,34 @@
 #
 #
 
-DIR=@SS_DIR@
+DIR="${DIR-@datadir@/ss}"
+SS_DIR=@SS_DIR@
 AWK=@AWK@
 SED=@SED@
+
+if test "x$1" = x ; then
+    echo "Usage: mk_cmds file"
+    exit 1
+fi
+
+if test ! -f $DIR/ct_c.sed -o ! -f $DIR/ct_c.awk ; then
+    DIR=$SS_DIR
+#    echo "Falling back to $DIR..."
+    if test ! -f $DIR/ct_c.sed -o ! -f $DIR/ct_c.awk ; then
+	echo "compile_et: Couldn't find compile_et's template files."
+	exit 1
+    fi
+fi
 
 FILE=$1
 ROOT=`echo $1 | sed -e s/.ct$//`
 BASE=`basename $ROOT`
 TMP=ct$$.c
+
+if ! test -f $FILE ; then
+    echo "$FILE: File not found"
+    exit 1;
+fi
 
 ${SED} -f ${DIR}/ct_c.sed  ${FILE} \
 	| ${AWK} -f ${DIR}/ct_c.awk rootname=${ROOT} outfile=${TMP} -
