tests: use /tmp for scratch files
The /tmp directory is often a memory based file system, and using this
can speed up running the regression test suite.

Signed-off-by: "Theodore Ts'o" <tytso@mit.edu>

diff --git a/tests/m_mkfs_overhead/script b/tests/m_mkfs_overhead/script
--- a/tests/m_mkfs_overhead/script
+++ b/tests/m_mkfs_overhead/script
@@ -1,5 +1,33 @@
-DESCRIPTION="test bg overhead calculation"
+echo -n "test bg overhead calculation: "
+
+OUT=$test_name.log
+EXP=$test_dir/expect
 FS_SIZE=1024
 MKE2FS_OPTS="-b 1024 -m 0 -g 256 -N 3745"
-. $cmd_dir/run_mke2fs
 
+MKE2FS_SKIP_PROGRESS=true
+MKE2FS_SKIP_CHECK_MSG=true
+export MKE2FS_SKIP_PROGRESS MKE2FS_SKIP_CHECK_MSG
+> $TMPFILE
+
+cp /dev/null $OUT
+
+$MKE2FS -F -o Linux $MKE2FS_OPTS $TMPFILE $FS_SIZE 2>&1 | sed -e 1d | \
+	sed -e "s;$TMPFILE;test.img;" | tr -d \\015 > $OUT
+
+rm -f $TMPFILE
+
+rm -f $test_name.ok $test_name.failed
+cmp -s $OUT $EXP
+status1=$?
+
+if [ "$status1" = 0 ] ; then
+	echo "ok"
+	touch $test_name.ok
+else
+	echo "failed"
+	diff $DIFF_OPTS $EXP $OUT > $test_name.failed
+fi
+rm -f tmp_expect
+
+unset OUT EXP DESCRIPTION FS_SIZE MKE2FS_OPTS MKE2FS_SKIP_PROGRESS
